# Generated by Django 4.2.4 on 2023-08-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='userrname',
            new_name='username',
        ),
    ]
