# Generated by Django 3.2.12 on 2023-08-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_userrname_member_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
                ('coursecode', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
